# Generated by Django 2.1.4 on 2018-12-17 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20181217_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='data',
        ),
        migrations.AddField(
            model_name='exame',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
