# Generated by Django 2.1.4 on 2018-12-17 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181217_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
