# Generated by Django 2.1.4 on 2018-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exame_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
