# Generated by Django 2.1.4 on 2018-12-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
        ('core', '0005_auto_20181217_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='medico',
            field=models.ManyToManyField(to='medico.Medico'),
        ),
    ]
