# Generated by Django 2.1.4 on 2018-12-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
        ('core', '0006_exame_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='medico',
        ),
        migrations.AddField(
            model_name='exame',
            name='medico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.Medico'),
        ),
    ]
