# Generated by Django 2.1.4 on 2018-12-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        ('core', '0007_auto_20181217_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='clinica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.Clinica'),
        ),
        migrations.AddField(
            model_name='exame',
            name='exame',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
