# Generated by Django 2.1.4 on 2018-12-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=60)),
                ('senha', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=10)),
                ('aprovado', models.BooleanField(default=False)),
            ],
        ),
    ]
