# Generated by Django 2.1.4 on 2018-12-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('senha', models.CharField(max_length=10)),
                ('especialidade', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('aprovado', models.BooleanField(default=False)),
            ],
        ),
    ]
